# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'MapApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'GoogleMaps'
   pod 'GooglePlaces'
   pod 'Apollo'
   pod 'Socket.IO-Client-Swift'
  target 'MapAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MapAppUITests' do
    # Pods for testing
  end

end
